<Type Name="StackOverflowException" FullName="System.StackOverflowException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="81a268653c2ab7d911f3033653886c2ce706ba72" />
    <Meta Name="ms.sourcegitcommit" Value="d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="ja-JP" />
    <Meta Name="ms.lasthandoff" Value="04/03/2018" />
  </Metadata>
  <TypeSignature Language="C#" Value="public sealed class StackOverflowException : SystemException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit StackOverflowException extends System.SystemException" />
  <TypeSignature Language="DocId" Value="T:System.StackOverflowException" />
  <TypeSignature Language="VB.NET" Value="Public NotInheritable Class StackOverflowException&#xA;Inherits SystemException" />
  <TypeSignature Language="C++ CLI" Value="public ref class StackOverflowException sealed : SystemException" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.SystemException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute>
      <AttributeName>System.Runtime.InteropServices.ComVisible(true)</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
      <span data-ttu-id="2978e-101">入れ子になったメソッド呼び出しが多くなりすぎ、実行スタックがオーバーフローした場合にスローされる例外。</span>
      <span class="sxs-lookup">
        <span data-stu-id="2978e-101">The exception that is thrown when the execution stack overflows because it contains too many nested method calls.</span>
      </span>
      <span data-ttu-id="2978e-102">このクラスは継承できません。</span>
      <span class="sxs-lookup">
        <span data-stu-id="2978e-102">This class cannot be inherited.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="2978e-103"><xref:System.StackOverflowException> 通常深いか、無限再帰が発生した場合、実行スタックのオーバーフロー エラーがスローされます。</span><span class="sxs-lookup"><span data-stu-id="2978e-103"><xref:System.StackOverflowException> is thrown for execution stack overflow errors, typically in case of a very deep or unbounded recursion.</span></span>  
  
 <span data-ttu-id="2978e-104"><xref:System.StackOverflowException> 値は 0x800703E9 HRESULT COR_E_STACKOVERFLOW を使用します。</span><span class="sxs-lookup"><span data-stu-id="2978e-104"><xref:System.StackOverflowException> uses the HRESULT COR_E_STACKOVERFLOW, which has the value 0x800703E9.</span></span> <span data-ttu-id="2978e-105"><xref:System.Reflection.Emit.OpCodes.Localloc>中間言語 (IL) の命令をスロー<xref:System.StackOverflowException>です。</span><span class="sxs-lookup"><span data-stu-id="2978e-105">The <xref:System.Reflection.Emit.OpCodes.Localloc> intermediate language (IL) instruction throws <xref:System.StackOverflowException>.</span></span> <span data-ttu-id="2978e-106">初期プロパティ値の一覧については、<xref:System.StackOverflowException>オブジェクトを参照してください、<xref:System.StackOverflowException.%23ctor%2A>コンス トラクターです。</span><span class="sxs-lookup"><span data-stu-id="2978e-106">For a list of initial property values for a <xref:System.StackOverflowException> object, see the <xref:System.StackOverflowException.%23ctor%2A> constructors.</span></span>  
  
## <a name="version-considerations"></a><span data-ttu-id="2978e-107">バージョンの考慮事項</span><span class="sxs-lookup"><span data-stu-id="2978e-107">Version Considerations</span></span>  
 <span data-ttu-id="2978e-108">.NET Framework 1.0 および 1.1 では、キャッチする可能性があります、<xref:System.StackOverflowException>オブジェクト (たとえば、無限再帰から回復する場合)。</span><span class="sxs-lookup"><span data-stu-id="2978e-108">In the .NET Framework 1.0 and 1.1, you could catch a <xref:System.StackOverflowException> object (for example, to recover from unbounded recursion).</span></span> <span data-ttu-id="2978e-109">以降、.NET Framework 2.0 をキャッチできません、<xref:System.StackOverflowException>オブジェクトを`try` / `catch`ブロック、および対応するプロセスは既定では終了します。</span><span class="sxs-lookup"><span data-stu-id="2978e-109">Starting with the .NET Framework 2.0, you can’t catch a <xref:System.StackOverflowException> object with a `try`/`catch` block, and the corresponding process is terminated by default.</span></span> <span data-ttu-id="2978e-110">そのため、検出し、スタック オーバーフローを防止するコードを記述する必要があります。</span><span class="sxs-lookup"><span data-stu-id="2978e-110">Consequently, you should write your code to detect and prevent a stack overflow.</span></span> <span data-ttu-id="2978e-111">たとえば、アプリは、再帰に依存している場合を使用してカウンターまたは状態の条件を再帰的なループを終了します。</span><span class="sxs-lookup"><span data-stu-id="2978e-111">For example, if your app depends on recursion, use a counter or a state condition to terminate the recursive loop.</span></span> <span data-ttu-id="2978e-112">次の例に再帰の数が呼び出していることを確認するカウンターを使用して、 `Execute` MAX_RECURSIVE_CALLS 定数によって定義されている最大数を超えないメソッドです。</span><span class="sxs-lookup"><span data-stu-id="2978e-112">The following example uses a counter to ensure that the number of recursive calls to the `Execute` method do not exceed a maximum defined by the MAX_RECURSIVE_CALLS constant.</span></span>  
  
 [!code-csharp[System.StackOverflowException.Class#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.stackoverflowexception.class/cs/example1a.cs#1)]
 [!code-vb[System.StackOverflowException.Class#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.stackoverflowexception.class/vb/example1a.vb#1)]  
  
> [!NOTE]
>  <span data-ttu-id="2978e-113">適用する、<xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>属性をスローするメソッドを<xref:System.StackOverflowException>も何も起こりません。</span><span class="sxs-lookup"><span data-stu-id="2978e-113">Applying the <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> attribute to a method that throws a <xref:System.StackOverflowException> has no effect.</span></span> <span data-ttu-id="2978e-114">引き続き、ユーザー コードから例外を処理することはできません。</span><span class="sxs-lookup"><span data-stu-id="2978e-114">You still cannot handle the exception from user code.</span></span>  
  
 <span data-ttu-id="2978e-115">アプリでは、共通言語ランタイム (CLR) をホストしている場合、CLR がスタック オーバーフロー例外が発生し、続行、対応するプロセスのアプリケーション ドメインをアンロードする必要がありますを指定できます。</span><span class="sxs-lookup"><span data-stu-id="2978e-115">If your app hosts the common language runtime (CLR), it can specify that the CLR should unload the application domain where the stack overflow exception occurs and let the corresponding process continue.</span></span> <span data-ttu-id="2978e-116">詳細については、次を参照してください。 [ICLRPolicyManager インターフェイス](~/docs/framework/unmanaged-api/hosting/iclrpolicymanager-interface.md)です。</span><span class="sxs-lookup"><span data-stu-id="2978e-116">For more information, see [ICLRPolicyManager Interface](~/docs/framework/unmanaged-api/hosting/iclrpolicymanager-interface.md).</span></span>  
  
 ]]></format>
    </remarks>
    <altmember cref="T:System.Exception" />
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="2978e-117">
            <see cref="T:System.StackOverflowException" /> クラスの新しいインスタンスを初期化します。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-117">Initializes a new instance of the <see cref="T:System.StackOverflowException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public StackOverflowException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.StackOverflowException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; StackOverflowException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="2978e-118">
            <see cref="T:System.StackOverflowException" /> クラスの新しいインスタンスの <see cref="P:System.Exception.Message" /> プロパティに、"要求された操作によってスタック オーバーフローが発生しました。" などのエラーを説明するシステムから提供されるメッセージを設定して、その新しいインスタンスを初期化します。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-118">Initializes a new instance of the <see cref="T:System.StackOverflowException" /> class, setting the <see cref="P:System.Exception.Message" /> property of the new instance to a system-supplied message that describes the error, such as "The requested operation caused a stack overflow."</span>
          </span>
          <span data-ttu-id="2978e-119">このメッセージには、現在のシステムのカルチャが考慮されます。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-119">This message takes into account the current system culture.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="2978e-120"><xref:System.StackOverflowException> のインスタンスの初期プロパティ値を次の表に示します。</span><span class="sxs-lookup"><span data-stu-id="2978e-120">The following table shows the initial property values for an instance of <xref:System.StackOverflowException>.</span></span>  
  
|<span data-ttu-id="2978e-121">プロパティ</span><span class="sxs-lookup"><span data-stu-id="2978e-121">Property</span></span>|<span data-ttu-id="2978e-122">[値]</span><span class="sxs-lookup"><span data-stu-id="2978e-122">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="2978e-123">`null`。</span><span class="sxs-lookup"><span data-stu-id="2978e-123">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="2978e-124">ローカライズされたエラー メッセージ文字列。</span><span class="sxs-lookup"><span data-stu-id="2978e-124">The localized error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public StackOverflowException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.StackOverflowException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; StackOverflowException(System::String ^ message);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="2978e-125">エラーを説明する <see cref="T:System.String" />。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-125">A <see cref="T:System.String" /> that describes the error.</span>
          </span>
          <span data-ttu-id="2978e-126">メッセージの内容は、ユーザーが理解できる内容にします。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-126">The content of message is intended to be understood by humans.</span>
          </span>
          <span data-ttu-id="2978e-127">このコンストラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認しておく必要があります。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-127">The caller of this constructor is required to ensure that this string has been localized for the current system culture.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="2978e-128">指定したエラー メッセージを使用して、<see cref="T:System.StackOverflowException" /> クラスの新しいインスタンスを初期化します。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-128">Initializes a new instance of the <see cref="T:System.StackOverflowException" /> class with a specified error message.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="2978e-129"><xref:System.StackOverflowException> のインスタンスの初期プロパティ値を次の表に示します。</span><span class="sxs-lookup"><span data-stu-id="2978e-129">The following table shows the initial property values for an instance of <xref:System.StackOverflowException>.</span></span>  
  
|<span data-ttu-id="2978e-130">プロパティ</span><span class="sxs-lookup"><span data-stu-id="2978e-130">Property</span></span>|<span data-ttu-id="2978e-131">[値]</span><span class="sxs-lookup"><span data-stu-id="2978e-131">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="2978e-132">null 参照 (Visual Basic の場合は `Nothing`)。</span><span class="sxs-lookup"><span data-stu-id="2978e-132">A null reference (`Nothing` in Visual Basic).</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="2978e-133">エラー メッセージ文字列。</span><span class="sxs-lookup"><span data-stu-id="2978e-133">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public StackOverflowException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.StackOverflowException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; StackOverflowException(System::String ^ message, Exception ^ innerException);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="2978e-134">例外の原因を説明するエラー メッセージ。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-134">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="2978e-135">現在の例外の原因となった例外。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-135">The exception that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="2978e-136">
            <c>innerException</c> パラメーターが null 参照 (Visual Basic の場合は <see langword="Nothing" />) でない場合は、内部例外を処理する <see langword="catch" /> ブロックで現在の例外が発生します。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-136">If the <c>innerException</c> parameter is not a null reference (<see langword="Nothing" /> in Visual Basic), the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="2978e-137">指定したエラー メッセージおよびこの例外の原因となった内部例外への参照を使用して、<see cref="T:System.StackOverflowException" /> クラスの新しいインスタンスを初期化します。</span>
          <span class="sxs-lookup">
            <span data-stu-id="2978e-137">Initializes a new instance of the <see cref="T:System.StackOverflowException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="2978e-138">前の例外の直接の結果としてスローされる例外は、<xref:System.Exception.InnerException%2A> プロパティに前の例外への参照を含んでいる場合があります。</span><span class="sxs-lookup"><span data-stu-id="2978e-138">An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="2978e-139"><xref:System.Exception.InnerException%2A> プロパティは、コンストラクターに渡されたものと同じ値を返します。`Nothing` プロパティによって内部例外値がコンストラクターに渡されなかった場合は、null 参照 (Visual Basic の場合は <xref:System.Exception.InnerException%2A>) を返します。</span><span class="sxs-lookup"><span data-stu-id="2978e-139">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="2978e-140"><xref:System.StackOverflowException> のインスタンスの初期プロパティ値を次の表に示します。</span><span class="sxs-lookup"><span data-stu-id="2978e-140">The following table shows the initial property values for an instance of <xref:System.StackOverflowException>.</span></span>  
  
|<span data-ttu-id="2978e-141">プロパティ</span><span class="sxs-lookup"><span data-stu-id="2978e-141">Property</span></span>|<span data-ttu-id="2978e-142">[値]</span><span class="sxs-lookup"><span data-stu-id="2978e-142">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="2978e-143">内部例外の参照。</span><span class="sxs-lookup"><span data-stu-id="2978e-143">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="2978e-144">エラー メッセージ文字列。</span><span class="sxs-lookup"><span data-stu-id="2978e-144">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
      </Docs>
    </Member>
  </Members>
</Type>